# ========== Profile ========== #
# avatar
avatar: http://image.fujs.top/saber.jpeg
# author name
author: Faith
# signature
signature: JSer
# SNS (you can custom the order)
social:
  email: 641084662@qq.com
  github: https://github.com/FaithGit
  # wechat and qq should be a path of qr-code image
  wechat: http://image.fujs.top/wechat.png
  qq: 
  telegram: 
  weibo: 
  zhihu: 
  douban: 
  facebook: 
  twitter: 
  instagram: 
  stack-overflow: 
  segmentFault: 
  juejin: 
  v2ex: 
  bilibili: 
  linkedin: 
  steam: 
  others: 
  rss: 
# friends
friends:
  ğŸŒˆå°å°¾å·´: //www.ixiaowei8.com
  friendB: 
  friendC: 
about:
  enable: true
  image: '/intro/about-bg.jpg'

# ========== Site ========== #
# title of the site (good for SEO)
SEO_title: Faith's Blog
# keywords for site (good for SEO)
SEO_keywords:
  - hexo
  - 'faith blog'
# main title shown in header image
main_title: Faith's Blog.
# subtitle
subtitle: å¥½çš„åŸŸåæˆ‘ä»¬å·²ç»ä¹°ä¸åˆ°äº†
# site haeder image
site_header_image: http://image.fujs.top/index-bg.jpg
# post haeder image
# post_header_image: https://unsplash.it/1600/900?random
post_header_image: https://uploadbeta.com/api/pictures/random/?key=BingEverydayWallpaperPicture
# 404 image
_404_image: http://image.fujs.top/404.jpg

# ========== Search ========== #
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We did not find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid: MTAyMC8zNDYyOS8xMTE2Nw==
  # Disqus  site: https://disqus.com/
  disqus_shortname: 
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner: 
  gitment_repo: 
  gitment_client_id: 
  gitment_client_secret: 
  # Youyan  site: http://www.uyan.cc/
  youyan_uid: 
  # Valine  site: https://valine.js.org/
  valine_appId: 
  valine_appKey: 
  valine_placeHolder: 

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: true
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} :)'
# Baidu analytics
baidu_analytics: 
# Google analytics
google_analytics: 
# CNZZ analytics
CNZZ_analytics: 

# ========== Others ========== #
# favicon
favicon: /avatar/saber.jpeg
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 
# enable toc
toc: true
# word count & reading time
reading_info: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 50
about_intro_height: 50
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: 'æœ¬æ–‡é‡‡ç”¨<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨ 4.0 å›½é™…è®¸å¯åè®®</a>è¿›è¡Œè®¸å¯'
